# Generated by Django 3.0.8 on 2020-08-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0002_auto_20200823_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='vendor',
        ),
    ]
